packages:
  - apps/*
  - packages/*

catalog:
  "@crxjs/vite-plugin": "2.0.0-beta.28"
  "@types/chrome": "^0.0.283"
  "@types/firefox-webext-browser": "^120.0.4"
  "@types/node": "^20.14.8"
  "@types/webextension-polyfill": "^0.12.1"
  "@solidjs/router": "^0.15.1"
  "@suid/vite-plugin": "^0.3.1"
  "@suid/material": "^0.18.0"
  "@suid/icons-material": "^0.8.1"
  "nanoid": "^5.0.8"
  "sass-embedded": "^1.81.0"
  "solid-devtools": "^0.30.1"
  "solid-js": "^1.9.3"
  "typescript": "^5.6.3"
  "vite-plugin-solid": "^2.10.2"
  "vite": "^5.4.11"
  "webextension-polyfill": "^0.12.0"
