packages:
  - apps/*
  - packages/*

catalog:
  "@crxjs/vite-plugin": "2.0.0-beta.28"
  "@types/chrome": "^0.0.283"
  "@types/node": "^20.14.8"
  "@suid/vite-plugin": "^0.3.1"
  "nanoid": "^5.0.8"
  "sass-embedded": "^1.81.0"
  "solid-devtools": "^0.30.1"
  "solid-js": "^1.9.3"
  "typescript": "^5.6.3"
  "vite-plugin-solid": "^2.10.2"
  "vite": "^5.4.11"
